version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    environment:
      - INDEX=FALSE
      - PORT=$PORT
      - MONGODB_URI=$MONGODB_URI
      - LOG_LEVEL=$LOG_LEVEL
      - WEBSOCKET_URL=$WEBSOCKET_URL
    ports:
      - 4000:4000
