version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app/
    working_dir: /usr/src/app
    environment:
      - PORT=4000
      - MONGOOSE_URL=mongodb://mongo:27017/typescript_mongoose
    ports:
      - 4000:4000
  mongo:
    image: "mongo"
    environment:
      - MONGO_INITDB_DATABASE=mongo-test-db
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    expose:
      - 27017
